- hosts: me
  name: Creating user and giving it sudo priv
  become: true
  vars:
    username: "labAnsible"
    passwd: "qwerty"
  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        password: "{{ passwd | password_hash('sha512') }}"
        state: present        

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
